---
- name: Build and deploy PHP app on TEST
  hosts: test
  become: yes
  vars:
    repo_url: "https://github.com/prathikp1403/projCert.git"
    workdir: "/opt/projCert"
    image_name: "walletapp:latest"
    container_name: "wallet"
    repo_branch: "master"   # change to "main" if your repo uses main

  tasks:
    - name: Ensure prerequisites present (git + docker client)
      ansible.builtin.apt:
        name:
          - git
          - docker.io
        state: present
        update_cache: yes

    - name: Ensure workdir exists
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: directory
        mode: '0755'

    - name: Clone/update repo (selected branch)
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ workdir }}"
        version: "{{ repo_branch }}"
        force: true

    - name: Build Docker image on TEST
      ansible.builtin.command:
        argv:
          - docker
          - build
          - -t
          - "{{ image_name }}"
          - -f
          - docker/Dockerfile
          - .
      args:
        chdir: "{{ workdir }}"

    - name: Stop old container if exists
      ansible.builtin.command:
        argv: [docker, rm, -f, "{{ container_name }}"]
      ignore_errors: yes

    - name: Run new container from built image (Apache foreground)
      ansible.builtin.command:
        argv:
          - docker
          - run
          - -d
          - --restart=always
          - --name
          - "{{ container_name }}"
          - -p
          - "80:80"
          - "{{ image_name }}"
          - apache2ctl
          - -D
          - FOREGROUND
