---
- name: Install Docker on test server(s)
  hosts: test
  become: yes
  tasks:
    - name: Install docker.io
      apt:
        name: docker.io
        update_cache: yes
        state: present
    - name: Ensure docker running
      service:
        name: docker
        state: started
        enabled: yes
